name: Entrega continua

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}    # AWS_ACCESS_KEY_ID
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}  # AWS_SECRET_ACCESS_KEY
        aws-region: us-east-1

    - name: Obtendo arquivo da tarefa
      run: aws ecs describe-task-definition --task-definition Tarefa_API-Go --query taskDefinition > task-definition.json